# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 485c8c505d993980318f16bef2f99289826be7b912709a44035bcf7c58bc2f469955faf2e70b344ca0e3ea40ac50832fbfd02893a1755d88e4c06c05f994b178

test:
  secret_key_base: 83188aabfe94bd39d250f05903a8b76f3d62bbeda2be296849a0e96c58f2358f4669582bb8e60a0011a0dfa7fdfd5765ab454634818d8367cf72bded962e3102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
